services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    command: node ./bin/server.js
    env_file:
      - .env
    cpus: "0.3"
    mem_limit: "512m"
    restart: unless-stopped

  rasa:
    # image: rasa/rasa:latest-full
    # volumes:
    #   - "./rasa/:/app/"
    build:
      context: ./rasa
      dockerfile: Dockerfile
    ports:
      - "${RASA_PORT}:${RASA_PORT}"
    environment:
      - RASA_PORT=${RASA_PORT}
      - RASA_SECRET=${RASA_SECRET}
    # command: >
    #   run --enable-api --port ${RASA_PORT} -t ${RASA_SECRET}
    user: root
    cpus: "1"
    mem_limit: "2000m"
    restart: unless-stopped

